StoredConfig =  {
settings = {
  dodebuff = true,
  doheal = false ,
  dobuff = true,
  docure = false ,
  domelee = true,
  doraid = false ,
  dodrag = false ,
  domount = false ,
  mountcast = false ,
  dosit = false ,
  doforage = false ,
  sitmana = 90,
  sitendur = 90,
  sitaggro = 60,
  TankName = "automatic",
  TargetFilter = 1,
  petassist = false ,
  acleash = 100,
  followdistance = 20,
  zradius = 100,
  campRestDistance = 10,
  maCampAnchor = true,
  engageXTargetOnly = false ,
  mezMinLevel = 0,
  charmPetAutoSetup = true,
  tankAllMobs = false ,
  aeTankIgnoreMezzer = false ,
  premem = true,
  campAcleash = true,
  upgradeCheck = true,
  autoScribe = true,
  confirmExit = false ,
},
pull = {
  spell = {
    gem = "melee",
    spell = "Brusco's Boastful Bellow",
  },
  radius = 1000,
  zrange = 200,
  pullMinCon = 2,
  pullMaxCon = 7,
  maxLevelDiff = 6,
  usePullLevels = false ,
  pullMinLevel = 1,
  pullMaxLevel = 125,
  chainpullhp = 0,
  chainpullcnt = 0,
  mana = 60,
  manaclass = { 'CLR' },
  leash = 500,
  fteLockoutSec = 120,
  backupCandidates = 3,
  addAbortRadius = 50,
  usepriority = false ,
  hunter = false ,
  roam = false ,
},
melee = {
  assistpct = 99,
  stickcmd = "hold uw 7",
  mobprobEngageGraceMs = 2000,
  stayBehind = true,
  behindAggroPct = 90,
  evadePct = 90,
  offtank = false ,
  mtSticky = false ,
  minmana = 0,
},
heal = {
  interruptlevel = 0.8,
  xttargets = 0,
  spells = {
  },
},
buff = {
  spells = {
    {
      gem = 5,
      spell = "McVaxius' Rousing Rondo",
      alias = "",
      enabled = true,
      inCombat = true,
      inIdle = false ,
      bands = {
        {
          targetphase = { 'groupbuff' },
          validtargets = { 'all' },
        },
      },
    },
    {
      gem = 6,
      spell = "Selo's Accelerando",
      alias = "selos",
      minmana = 0,
      enabled = true,
      inCombat = false ,
      inIdle = true,
      combatOnly = false ,
      bands = {
        {
          targetphase = { 'groupbuff' },
          validtargets = { 'all' },
        },
      },
      spellicon = 0,
    },
    {
      gem = 8,
      spell = "Cantata of Replenishment",
      alias = "manasong",
      minmana = 0,
      enabled = true,
      inCombat = true,
      inIdle = true,
      combatOnly = false ,
      bands = {
        {
          targetphase = { 'groupbuff' },
          validtargets = { 'all' },
        },
      },
      spellicon = 0,
    },
    {
      gem = 4,
      spell = "Tarew's Aquatic Ayre",
      alias = "eb",
      minmana = 0,
      enabled = false ,
      inCombat = true,
      inIdle = true,
      combatOnly = false ,
      bands = {
        {
          targetphase = { 'groupbuff' },
          validtargets = { 'all' },
        },
      },
      spellicon = 0,
    },
    {
      gem = 7,
      spell = "Composition of Ervaj",
      alias = "overhaste",
      minmana = 0,
      enabled = false ,
      inCombat = true,
      inIdle = false ,
      combatOnly = false ,
      bands = {
        {
          targetphase = { 'groupbuff' },
          validtargets = { 'all' },
        },
      },
      spellicon = 0,
    },
    {
      gem = 4,
      spell = "Elemental Rhythms",
      alias = false ,
      minmana = 0,
      enabled = false ,
      inCombat = true,
      inIdle = true,
      combatOnly = false ,
      bands = {
        {
          targetphase = { 'groupbuff' },
          validtargets = { 'all' },
        },
      },
      spellicon = 0,
    },
  },
},
debuff = {
  spells = {
    {
      gem = 3,
      spell = "Song of Twilight",
      alias = "mez",
      minmana = 0,
      enabled = true,
      bands = {
        {
          targetphase = { 'notmatar' },
          validtargets = {  },
          min = 0,
          max = 100,
          mintar = 2,
        },
      },
      recast = 0,
      delay = 0,
      dontStack = { 'Mezzed' },
    },
    {
      gem = 1,
      spell = "Selo's Consonant Chain",
      alias = "snare",
      minmana = 0,
      enabled = true,
      bands = {
        {
          targetphase = { 'matar' },
          validtargets = {  },
          min = 0,
          max = 50,
        },
      },
      recast = 0,
      delay = 0,
      dontStack = { 'Snared' },
    },
    {
      gem = 2,
      spell = "Tuyen's Chant of Flame",
      alias = false ,
      minmana = 0,
      enabled = false ,
      bands = {
        {
          targetphase = { 'matar' },
          validtargets = {  },
          min = 0,
          max = 99,
        },
      },
      recast = 0,
      delay = 0,
    },
    {
      gem = 4,
      spell = "Occlusion of Sound",
      alias = false ,
      minmana = 0,
      enabled = true,
      bands = {
        {
          targetphase = { 'matar' },
          validtargets = {  },
          min = 20,
          max = 100,
        },
      },
      recast = 0,
      delay = 0,
      stopWhen = { 'Slowed' },
    },
  },
},
cure = {
  spells = {
  },
},
script = {
},
roles = {
  tank = {
    domelee = true,
    doheal = false ,
    docure = true,
    dobuff = true,
    dodebuff = false ,
    dosit = true,
    mtSticky = true,
    offtank = false ,
    engageXTargetOnly = false ,
    setTank = true,
    setAssist = false ,
  },
  ma = {
    domelee = true,
    doheal = false ,
    docure = true,
    dobuff = true,
    dodebuff = true,
    dosit = true,
    mtSticky = false ,
    offtank = false ,
    engageXTargetOnly = false ,
    setTank = false ,
    setAssist = true,
  },
  dps = {
    domelee = true,
    doheal = false ,
    docure = true,
    dobuff = true,
    dodebuff = true,
    dosit = true,
    mtSticky = false ,
    offtank = false ,
    engageXTargetOnly = false ,
    setTank = false ,
    setAssist = false ,
  },
  healer = {
    domelee = false ,
    doheal = true,
    docure = true,
    dobuff = true,
    dodebuff = false ,
    dosit = true,
    mtSticky = false ,
    offtank = false ,
    engageXTargetOnly = false ,
    setTank = false ,
    setAssist = false ,
  },
},
}
return StoredConfig