StoredConfig =  {
settings = {
  dodebuff = false ,
  doheal = true,
  dobuff = true,
  docure = false ,
  domelee = false ,
  doraid = false ,
  dodrag = false ,
  domount = false ,
  mountcast = false ,
  dosit = true,
  doforage = false ,
  doChchain = true,
  sitmana = 90,
  sitendur = 90,
  sitaggro = 60,
  TankName = "automatic",
  TargetFilter = 1,
  petassist = false ,
  acleash = 60,
  followdistance = 20,
  zradius = 100,
  campRestDistance = 10,
  maCampAnchor = true,
  engageXTargetOnly = false ,
  mezMinLevel = 0,
  charmPetAutoSetup = true,
  tankAllMobs = false ,
  aeTankIgnoreMezzer = false ,
  premem = true,
  campAcleash = true,
  upgradeCheck = true,
  autoScribe = true,
  confirmExit = false ,
  antiAfk = true,
},
pull = {
  spell = {
    gem = "melee",
    spell = "",
  },
  radius = 400,
  zrange = 150,
  pullMinCon = 2,
  pullMaxCon = 5,
  maxLevelDiff = 6,
  usePullLevels = false ,
  pullMinLevel = 1,
  pullMaxLevel = 125,
  chainpullhp = 0,
  chainpullcnt = 0,
  mana = 60,
  manaclass = { 'CLR', 'DRU', 'SHM' },
  leash = 500,
  fteLockoutSec = 120,
  backupCandidates = 3,
  addAbortRadius = 50,
  usepriority = false ,
  hunter = false ,
  roam = false ,
},
melee = {
  assistpct = 99,
  stickcmd = "hold uw 7",
  mobprobEngageGraceMs = 1000,
  stayBehind = false ,
  behindAggroPct = 90,
  evadePct = 90,
  offtank = false ,
  mtSticky = false ,
  minmana = 0,
},
heal = {
  interruptlevel = 0.8,
  xttargets = 0,
  spells = {
    {
      gem = 4,
      spell = "Word of Healing",
      alias = "grpheal",
      minmana = 0,
      minmanapct = 0,
      maxmanapct = 100,
      enabled = true,
      inCombat = false ,
      tarcnt = 2,
      bands = {
        {
          targetphase = { 'groupheal' },
          validtargets = { 'all' },
          min = 0,
          max = 75,
        },
      },
      healResource = "hp",
    },
    {
      gem = 5,
      spell = "Celestial Elixir",
      alias = "hot",
      minmana = 0,
      minmanapct = 0,
      maxmanapct = 100,
      enabled = true,
      inCombat = false ,
      bands = {
        {
          targetphase = { 'self', 'groupmember' },
          validtargets = { 'all' },
          min = 61,
          max = 80,
        },
      },
      healResource = "hp",
    },
    {
      gem = 1,
      spell = "Divine Light",
      alias = "heal",
      enabled = true,
      bands = {
        {
          targetphase = { 'self', 'groupmember', 'pc', 'tank' },
          validtargets = { 'war', 'mnk', 'enc', 'nec', 'clr', 'rog', 'shd', 'brd', 'dru', 'wiz', 'bst', 'pal', 'rng', 'ber', 'mag', 'shm' },
          min = 0,
          max = 60,
        },
      },
    },
    {
      gem = "item",
      spell = "Greaves of Stability",
      alias = "clickyheal",
      minmana = 0,
      minmanapct = 0,
      maxmanapct = 25,
      enabled = true,
      inCombat = false ,
      tarcnt = 2,
      bands = {
        {
          targetphase = { 'groupheal' },
          validtargets = { 'all' },
          min = 0,
          max = 80,
        },
      },
      healResource = "hp",
    },
    {
      gem = "item",
      spell = "Water Sprinkler of Nem Ankh",
      alias = "rez",
      minmana = 0,
      minmanapct = 0,
      maxmanapct = 100,
      enabled = true,
      inCombat = true,
      bands = {
        {
          targetphase = { 'corpse' },
          validtargets = { 'all' },
          min = 0,
          max = 60,
        },
      },
      healResource = "hp",
    },
  },
},
buff = {
  spells = {
    {
      gem = 6,
      spell = "Aegolism",
      alias = "aego",
      enabled = true,
      tarcnt = 1,
      bands = {
        {
          targetphase = { 'self', 'tank', 'groupmember' },
          validtargets = { 'all' },
        },
      },
    },
  },
},
debuff = {
  spells = {
    {
      gem = 7,
      spell = "Furor",
      alias = false ,
      minmana = 0,
      enabled = false ,
      bands = {
        {
          targetphase = { 'matar' },
          validtargets = {  },
          min = 50,
          max = 99,
        },
      },
      recast = 0,
      delay = 0,
    },
  },
},
cure = {
  spells = {
    {
      gem = 7,
      spell = "Cure Disease",
      alias = "curedisease",
      curetype = { 'disease' },
      enabled = true,
      bands = {
        {
          targetphase = { 'tank', 'self', 'groupmember' },
          validtargets = { 'all' },
        },
      },
    },
    {
      gem = 7,
      spell = "Cure Poison",
      alias = "curepoison",
      minmana = 0,
      curetype = { 'poison' },
      enabled = true,
      bands = {
        {
          targetphase = { 'self', 'tank', 'groupmember' },
          validtargets = { 'all' },
        },
      },
    },
  },
},
script = {
},
roles = {
  tank = {
    domelee = true,
    doheal = false ,
    docure = true,
    dobuff = true,
    dodebuff = false ,
    dosit = true,
    mtSticky = true,
    offtank = false ,
    engageXTargetOnly = false ,
    setTank = true,
    setAssist = false ,
  },
  ma = {
    domelee = true,
    doheal = false ,
    docure = true,
    dobuff = true,
    dodebuff = true,
    dosit = true,
    mtSticky = false ,
    offtank = false ,
    engageXTargetOnly = false ,
    setTank = false ,
    setAssist = true,
  },
  dps = {
    domelee = true,
    doheal = false ,
    docure = true,
    dobuff = true,
    dodebuff = true,
    dosit = true,
    mtSticky = false ,
    offtank = false ,
    engageXTargetOnly = false ,
    setTank = false ,
    setAssist = false ,
  },
  healer = {
    domelee = false ,
    doheal = true,
    docure = true,
    dobuff = true,
    dodebuff = false ,
    dosit = true,
    mtSticky = false ,
    offtank = false ,
    engageXTargetOnly = false ,
    setTank = false ,
    setAssist = false ,
  },
},
}
return StoredConfig