local registry = require('actornet.command_registry')
local rexec = require('actornet.rexec')

registry.bind('/anexecute', rexec.sendDirectCommand)
registry.bind('/anaexecute', rexec.sendGlobalCommand)
registry.bind('/anaaexecute', rexec.sendSelfAndGlobalCommand)
registry.bind('/anzaexecute', rexec.sendSelfAndZoneCommand)
registry.bind('/anzexecute', rexec.sendZoneCommand)
registry.bind('/angaexecute', rexec.sendSelfAndGroupCommand)
registry.bind('/angexecute', rexec.sendGroupCommand)
registry.bind('/anraexecute', rexec.sendSelfAndRaidCommand)
registry.bind('/anrexecute', rexec.sendRaidCommand)
